name: Build from Pull Request

on: [pull_request]

jobs:
  build-pr:
    strategy:
      matrix:
        # Use thses Java versions:
        java: [ 21 ] # Current Java LTS and current latest Java version
        # Use these operating systems:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Show Java version
        run: java -version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Show Gradle version
        run: gradle --version

      - name: Build with Gradle
        run: gradle getVersion build --stacktrace

      - name: Get Mod Name
        id: get_mod_name
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_name'
      - name: Get Mod Version
        id: get_mod_version
        run: |
          echo "mod_version=$(cat build/.reden-version)" >> $GITHUB_OUTPUT

      - name: Upload assets to GitHub Action
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: "[PR-CI#${{ github.run_number }}] ${{ steps.get_mod_name.outputs.mod_name }} ${{ steps.get_mod_version.outputs.mod_version }} - Java ${{ matrix.java }}"
          path: |
            build/libs/*.jar
            build/reports/tests/
