name: Build Stable Release version and Publish

on:
  release:
    # It is recommended to set the release tag as "v.<major>.<minor>-patch.<patch>" (e.g. "v.1.0-patch.1") when creating a release.
    types: [released]

jobs:
  build-and-publish-pre-release:
    strategy:
      matrix:
        # Use thses Java versions:
        java: [17] # Only use the latest Java LTS
        # Use these operating systems:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Show Java version
        run: java -version
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Show Gradle version
        run: gradle --version

      - name: Build with Gradle
        env:
          REDEN_BUILD_TYPE: "RELEASE"
        run: gradle getVersion build --stacktrace

      - name: Get Mod Name
        id: get_mod_name
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: 'mod_name'
      - name: Get Mod Version
        id: get_mod_version
        run: |
          echo "mod_version=$(cat build/.reden-short-version)" >> $GITHUB_OUTPUT

      - name: Upload assets to GitHub Action
        uses: actions/upload-artifact@v3
        with:
          name: "${{ steps.get_mod_name.outputs.mod_name }} ${{ steps.get_mod_version.outputs.mod_version }}"
          path: build/libs/*.jar

      - name: Publish to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: build/libs/*.jar
          body: "[RELEASE-CI#${{ github.run_number }}] ${{ steps.get_mod_name.outputs.mod_name }} Mod Stable Release ${{ steps.get_mod_version.outputs.mod_version }}"
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ github.event.ref }}

      - name: Publish to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Publish to Modrinth
          modrinth-id: xRu8OXEJ
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          # Publish to CurseForge
          curseforge-id: 903236
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          # Universal Configurations
          files: build/libs/*-@(stable).jar

          name: "${{ steps.get_mod_name.outputs.mod_name }} ${{ steps.get_mod_version.outputs.mod_version }}"
          version: "${{ steps.get_mod_version.outputs.mod_version }}"
          version-type: release

          loaders: fabric

          dependencies: |
            carpet
            malilib
            fabric-api
            fabric-language-kotlin
            owo-lib

          java: |
            17
            18
            19
            20
          retry-attempts: 2
          retry-delay: 10000
